# Generated by Django 5.0.7 on 2026-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ')),
                ('music_title', models.CharField(default='Midnight Protocol', max_length=200)),
                ('it_ad_title', models.CharField(default='Premium IT Support', max_length=200)),
                ('it_ad_desc', models.TextField(default='Get 15% off your first Starlink installation.')),
                ('it_ad_link', models.URLField(default='https://example.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
