# Generated by Django 5.0.7 on 2026-05-07 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_mediacontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='featured_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.promocode'),
        ),
    ]
