# Generated by Django 5.0.7 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_mediacontent_featured_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(default='YOUTHinIT', max_length=200)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
