# Generated by Django 5.0.7 on 2026-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_musictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlocation',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video for the landing page', null=True),
        ),
    ]
